<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JavaScriptEngineSwitcher.Jint" Version="[3.34.3,4)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Crawler.AngleSharp.Js\Crawler.AngleSharp.Js.csproj" />
  </ItemGroup>

</Project>
