<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="SimpleCrawler.Benchmarks" />
		<InternalsVisibleTo Include="SimpleCrawler.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\SimpleCrawler.AngleSharp\SimpleCrawler.AngleSharp.csproj" />
		<ProjectReference Include="..\..\src\SimpleCrawler.Js.Jint\SimpleCrawler.Js.Jint.csproj" />
		<ProjectReference Include="..\..\src\SimpleCrawler.Js.V8\SimpleCrawler.Js.V8.csproj" />
		<ProjectReference Include="..\..\src\SimpleCrawler.Core\SimpleCrawler.Core.csproj" />
		<ProjectReference Include="..\..\src\SimpleCrawler.HtmlAgilityPack\SimpleCrawler.HtmlAgilityPack.csproj" />
		<ProjectReference Include="..\..\src\SimpleCrawler.Playwright\SimpleCrawler.Playwright.csproj" />
		<ProjectReference Include="..\..\src\SimpleCrawler.Puppeteer\SimpleCrawler.Puppeteer.csproj" />
	</ItemGroup>

</Project>
